main: org.geysermc.addons.spigot.SpigotGeyserAddonBootstrap
name: ${name}
version: ${version}
website: https://geysermc.org
author: GeyserMC
description: ${description}
api-version: 1.13
softdepend: [floodgate-bukkit, PlaceholderAPI]